package me.hexf.nzcp;

import foundation.identity.did.DIDDocument;
import foundation.identity.did.VerificationMethod;
import me.hexf.nzcp.exceptions.*;
import me.hexf.nzcp.resolvers.StaticResolver;
import org.junit.Test;

import java.net.URI;
import java.net.URISyntaxException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Map;
import java.util.UUID;
import static org.junit.Assert.*;

public class V1PublicCovidPassTests {
    public static final String VALID_PAYLOAD = "NZCP:/1/2KCEVIQEIVVWK6JNGEASNICZAEP2KALYDZSGSZB2O5SWEOTOPJRXALTDN53GSZBRHEXGQZLBNR2GQLTOPICRUYMBTIFAIGTUKBAAUYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFTXMZLSONUW63TFGEXDALRQMR2HS4DFQJ2FMZLSNFTGSYLCNRSUG4TFMRSW45DJMFWG6UDVMJWGSY2DN53GSZCQMFZXG4LDOJSWIZLOORUWC3CTOVRGUZLDOSRWSZ3JOZSW4TTBNVSWISTBMNVWUZTBNVUWY6KOMFWWKZ2TOBQXE4TPO5RWI33CNIYTSNRQFUYDILJRGYDVAYFE6VGU4MCDGK7DHLLYWHVPUS2YIDJOA6Y524TD3AZRM263WTY2BE4DPKIF27WKF3UDNNVSVWRDYIYVJ65IRJJJ6Z25M2DO4YZLBHWFQGVQR5ZLIWEQJOZTS3IQ7JTNCFDX";
    public static final String BAD_PUBLIC_KEY_PAYLOAD = "NZCP:/1/2KCEVIQEIVVWK6JNGEASNICZAEP2KALYDZSGSZB2O5SWEOTOPJRXALTDN53GSZBRHEXGQZLBNR2GQLTOPICRUYMBTIFAIGTUKBAAUYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFTXMZLSONUW63TFGEXDALRQMR2HS4DFQJ2FMZLSNFTGSYLCNRSUG4TFMRSW45DJMFWG6UDVMJWGSY2DN53GSZCQMFZXG4LDOJSWIZLOORUWC3CTOVRGUZLDOSRWSZ3JOZSW4TTBNVSWISTBMNVWUZTBNVUWY6KOMFWWKZ2TOBQXE4TPO5RWI33CNIYTSNRQFUYDILJRGYDVAY73U6TCQ3KF5KFML5LRCS5D3PCYIB2D3EOIIZRPXPUA2OR3NIYCBMGYRZUMBNBDMIA5BUOZKVOMSVFS246AMU7ADZXWBYP7N4QSKNQ4TETIF4VIRGLHOXWYMR4HGQ7KYHHU";
    public static final String UNLOCATABLE_PUBLIC_KEY_PAYLOAD = "NZCP:/1/2KCEVIQEIVVWK6JNGIASNICZAEP2KALYDZSGSZB2O5SWEOTOPJRXALTDN53GSZBRHEXGQZLBNR2GQLTOPICRUYMBTIFAIGTUKBAAUYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFTXMZLSONUW63TFGEXDALRQMR2HS4DFQJ2FMZLSNFTGSYLCNRSUG4TFMRSW45DJMFWG6UDVMJWGSY2DN53GSZCQMFZXG4LDOJSWIZLOORUWC3CTOVRGUZLDOSRWSZ3JOZSW4TTBNVSWISTBMNVWUZTBNVUWY6KOMFWWKZ2TOBQXE4TPO5RWI33CNIYTSNRQFUYDILJRGYDVBMP3LEDMB4CLBS2I7IOYJZW46U2YIBCSOFZMQADVQGM3JKJBLCY7ATASDTUYWIP4RX3SH3IFBJ3QWPQ7FJE6RNT5MU3JHCCGKJISOLIMY3OWH5H5JFUEZKBF27OMB37H5AHF";
    public static final String MODIFIED_SIGNATURE_PAYLOAD = "NZCP:/1/2KCEVIQEIVVWK6JNGEASNICZAEP2KALYDZSGSZB2O5SWEOTOPJRXALTDN53GSZBRHEXGQZLBNR2GQLTOPICRUYMBTIFAIGTUKBAAUYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFTXMZLSONUW63TFGEXDALRQMR2HS4DFQJ2FMZLSNFTGSYLCNRSUG4TFMRSW45DJMFWG6UDVMJWGSY2DN53GSZCQMFZXG4LDOJSWIZLOORUWC3CTOVRGUZLDOSRWSZ3JOZSW4TTBNVSWISTBMNVWUZTBNVUWY6KOMFWWKZ2TOBQXE4TPO5RWI33CNIYTSNRQFUYDILJRGYDVAYFE6VGU4MCDGK7DHLLYWHVPUS2YIAAAAAAAAAAAAAAAAC63WTY2BE4DPKIF27WKF3UDNNVSVWRDYIYVJ65IRJJJ6Z25M2DO4YZLBHWFQGVQR5ZLIWEQJOZTS3IQ7JTNCFDX";
    public static final String MODIFIED_PAYLOAD_PAYLOAD = "NZCP:/1/2KCEVIQEIVVWK6JNGEASNICZAEOKKALYDZSGSZB2O5SWEOTOPJRXALTDN53GSZBRHEXGQZLBNR2GQLTOPICRUYMBTIFAIGTUKBAAUYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFTXMZLSONUW63TFGEXDALRQMR2HS4DFQJ2FMZLSNFTGSYLCNRSUG4TFMRSW45DJMFWG6UDVMJWGSY2DN53GSZCQMFZXG4LDOJSWIZLOORUWC3CTOVRGUZLDOSRWSZ3JOZSW4TTBNVSWKU3UMV3GK2TGMFWWS3DZJZQW2ZLDIRXWKY3EN5RGUMJZGYYC2MBUFUYTMB2QMCSPKTKOGBBTFPRTVV4LD2X2JNMEAAAAAAAAAAAAAAAABPN3J4NASOBXVEC5P3FC52BWW2ZK3IR4EMKU7OUIUUU7M5OWNBXOMMVQT3CYDKYI64VULCIEXMZZNUIPUZWRCR3Q";
    public static final String EXPIRED_PAYLOAD = "NZCP:/1/2KCEVIQEIVVWK6JNGEASNICZAEP2KALYDZSGSZB2O5SWEOTOPJRXALTDN53GSZBRHEXGQZLBNR2GQLTOPICRUX5AM2FQIGTBPBPYWYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFTXMZLSONUW63TFGEXDALRQMR2HS4DFQJ2FMZLSNFTGSYLCNRSUG4TFMRSW45DJMFWG6UDVMJWGSY2DN53GSZCQMFZXG4LDOJSWIZLOORUWC3CTOVRGUZLDOSRWSZ3JOZSW4TTBNVSWISTBMNVWUZTBNVUWY6KOMFWWKZ2TOBQXE4TPO5RWI33CNIYTSNRQFUYDILJRGYDVA56TNJCCUN2NVK5NGAYOZ6VIWACYIBM3QXW7SLCMD2WTJ3GSEI5JH7RXAEURGATOHAHXC2O6BEJKBSVI25ICTBR5SFYUDSVLB2F6SJ63LWJ6Z3FWNHOXF6A2QLJNUFRQNTRU";
    public static final String BEFORE_VALID_PAYLOAD = "NZCP:/1/2KCEVIQEIVVWK6JNGEASNICZAEP2KALYDZSGSZB2O5SWEOTOPJRXALTDN53GSZBRHEXGQZLBNR2GQLTOPICRU2XI5UFQIGTMZIQIWYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFTXMZLSONUW63TFGEXDALRQMR2HS4DFQJ2FMZLSNFTGSYLCNRSUG4TFMRSW45DJMFWG6UDVMJWGSY2DN53GSZCQMFZXG4LDOJSWIZLOORUWC3CTOVRGUZLDOSRWSZ3JOZSW4TTBNVSWISTBMNVWUZTBNVUWY6KOMFWWKZ2TOBQXE4TPO5RWI33CNIYTSNRQFUYDILJRGYDVA27NR3GFF4CCGWF66QGMJSJIF3KYID3KTKCBUOIKIC6VZ3SEGTGM3N2JTWKGDBAPLSG76Q3MXIDJRMNLETOKAUTSBOPVQEQAX25MF77RV6QVTTSCV2ZY2VMN7FATRGO3JATR";


    public static final StaticResolver MOCK_RESOLVER = new StaticResolver.Builder()
            .addDocument(
                    URI.create("did:web:nzcp.covid19.health.nz"),
                    DIDDocument.builder()
                            .assertionMethodVerificationMethod(
                                    VerificationMethod.builder()
                                            .id(URI.create("did:web:nzcp.covid19.health.nz#key-1"))
                                            .publicKeyJwk(Map.of(
                                                    "kty", "EC",
                                                    "crv", "P-256",
                                                    "x", "zRR-XGsCp12Vvbgui4DD6O6cqmhfPuXMhi1OxPl8760",
                                                    "y", "Iv5SU6FuW-TRYh5_GOrJlcV_gpF_GpFQhCOD8LSk3T0"
                                            ))
                                            .build()
                            )
                            .build()
            )
            .build();

    public static Verifier VERIFIER = new Verifier.Builder()
        .addExampleTrustedIssuer()
        .setResolver(MOCK_RESOLVER)
        .build();

    @Test
    public void testQRCodeDecode() throws DecodingException, URISyntaxException {
        // Taken from https://nzcp.covid19.health.nz/#valid-worked-example

        CovidPass pass = CovidPass.createFromQRCodeString(VALID_PAYLOAD);

        assertEquals(pass.getKeyId(), "key-1");
        assertEquals(pass.getId(), UUID.fromString("60a4f54d-4e30-4332-be33-ad78b1eafa4b"));
        assertEquals(pass.getIssuer(), new URI("did:web:nzcp.covid19.health.nz"));
        assertEquals(pass.getNotValidAfter(), LocalDateTime.ofEpochSecond(1951416330L, 0, ZoneOffset.UTC));
        assertEquals(pass.getNotValidBefore(), LocalDateTime.ofEpochSecond(1635883530L, 0, ZoneOffset.UTC));

        assertEquals(pass.getCredentialSubject(),
                new CredentialSubject(
                        "Jack",
                        "Sparrow",
                        LocalDate.of(1960, 4, 16)
                )
            );
    }

    @Test
    public void verifyValidQRCode() throws DecodingException, DocumentResolvingException, VerificationException, NoSuchAlgorithmException, SignatureException, URISyntaxException, InvalidKeyException {
        CovidPass pass = CovidPass.createFromQRCodeString(VALID_PAYLOAD);
        Verifier.VerificationResult result = VERIFIER.verify(pass);

        assertTrue(result.isTrustedIssuer());
        assertFalse(result.isExpired());
    }

    @Test
    public void verifyBadPKQRCode() throws DecodingException {
        CovidPass pass = CovidPass.createFromQRCodeString(BAD_PUBLIC_KEY_PAYLOAD);

        assertThrows(SignatureMismatchException.class, () -> VERIFIER.verify(pass));
    }

    @Test
    public void verifyUnlocatablePKQRCode() throws DecodingException {
        CovidPass pass = CovidPass.createFromQRCodeString(UNLOCATABLE_PUBLIC_KEY_PAYLOAD);

        assertThrows(KeyNotFoundException.class, () -> VERIFIER.verify(pass));
    }

    @Test
    public void verifyModifiedSignatureQRCode() throws DecodingException {
        CovidPass pass = CovidPass.createFromQRCodeString(MODIFIED_SIGNATURE_PAYLOAD);

        assertThrows(SignatureMismatchException.class, () -> VERIFIER.verify(pass));
    }

    @Test
    public void verifyModifiedPayloadQRCode() throws DecodingException {
        CovidPass pass = CovidPass.createFromQRCodeString(MODIFIED_PAYLOAD_PAYLOAD);

        assertThrows(SignatureMismatchException.class, () -> VERIFIER.verify(pass));
    }

    @Test
    public void verifyExpiredPayload() throws DecodingException, DocumentResolvingException, VerificationException, NoSuchAlgorithmException, SignatureException, URISyntaxException, InvalidKeyException {
        CovidPass pass = CovidPass.createFromQRCodeString(EXPIRED_PAYLOAD);
        Verifier.VerificationResult result = VERIFIER.verify(pass);

        assertTrue(result.isTrustedIssuer());
        assertTrue(result.isExpired());
    }

    @Test
    public void verifyBeforeValidPayload() throws DecodingException, DocumentResolvingException, VerificationException, NoSuchAlgorithmException, SignatureException, URISyntaxException, InvalidKeyException {
        CovidPass pass = CovidPass.createFromQRCodeString(BEFORE_VALID_PAYLOAD);
        Verifier.VerificationResult result = VERIFIER.verify(pass);

        assertTrue(result.isTrustedIssuer());
        assertTrue(result.isExpired());
    }

}
